### ISSUE TITLE
Crash with latest release version of Bedrock Eco?

### ISSUE THREAD

**Issue by n00bslayr94** [cooldogepm/BedrockEconomyScore#3]
[Wed_Jan_10-21.44.46-GMT_2024.log](https://github.com/cooldogepm/BedrockEconomyScore/files/13894844/Wed_Jan_10-21.44.46-GMT_2024.log)

**Comment by cooldogedev** [comment]
Looks like you're using an outdated version of BedrockEconomy, use the [dev build](https://poggit.pmmp.io/ci/cooldogepm/BedrockEconomy/BedrockEconomy/dev:107)
