### ISSUE TITLE
How to use this

### ISSUE THREAD

**Issue by brghtestdev3** [cooldogepm/BedrockEconomyScore#4]
I want it to show my balance in scorehud, I use it doesn't work, how to fix it(I convert it zip to phar)

**Comment by b1zeyofficial** [comment]
Do you mean that ``public const TAG BALANCE = "bedrockeconomy.balance";`` does not update when using /setbalance ?

**Comment by brghtestdev3** [comment]
No, I use this in scorehud and not making plugins, so in scorehud I type like this "Money : {bedrockeconomy.balance" and it doesn't work only blank

**Comment by cooldogedev** [comment]
`{bedrockeconomy.balance}`
